spring:
  application:
    name: "Song Search"
    version: ^project.version^
    description: "Song Search API Documentation"

server:
  port: 8080

elastic:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  analysisCentricIndex: analysis_centric
  fileCentricIndex: file_centric

song-search:
  workflowRunParameterKeys:
    analysisId:
      - analysis_id
      - normal_aln_analysis_id
      - tumour_aln_analysis_id

## TODO spring profile
auth:
  jwtPublicKeyUrl: ""
  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQAB\n-----END PUBLIC KEY-----"
  graphqlScopes:
      queryOnly:
        - CLINICALSERVICE.WRITE
      queryAndMutation:
        - CLINICALSERVICE.WRITE

#AUTH_JWTPUBLICKEYURL
#AUTH_GRAQPHQLSCOPES_QUERYONLY_0
#AUTH_GRAQPHQLSCOPES_QUERYANDMUTATION_0
