spring:
  application:
    name: "Song Search"
    version: ^project.version^
    description: "Song Search API Documentation"

server:
  port: 8080

elastic:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  analysisCentricIndex: analysis_centric
  fileCentricIndex: file_centric

song-search:
  workflowRunParameterKeys:
    analysisId:
      - analysis_id
      - normal_aln_analysis_id
      - tumour_aln_analysis_id
